# Generated by Django 4.2.6 on 2023-10-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsal_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='curso',
            new_name='Usuario',
        ),
    ]
